import fsx from "fs-extra";
import mustache from "mustache";

import type { RenderOptions } from "./@types";

const generator = require("../package.json");

// disabling escape
mustache.escape = (s) => s;

export const BANNER = `/**
* @generated by ${generator.name}; do not modify manually!
*/`;

export async function render<Context = {}>(
  template: string,
  context: Context,
  opts?: RenderOptions,
): Promise<string> {
  const content = mustache.render(template, { ...context });
  return opts?.format ? opts.format(content) : content;
}

export async function renderToFile<Context = {}>(
  file: string,
  template: string,
  context: Context,
  opts?: RenderOptions,
): Promise<void> {
  return fsx.outputFile(file, await render(template, context, opts), "utf8");
}
